name: Docs
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    doc:
        name: Generate Docs
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: langroodi/doxygenize@v1
